/**
 * Share-card descriptors — the single source of truth for og:image / twitter:image.
 *
 * WHY THIS FILE EXISTS (truth audit 2026-07-31, finding TA-11 / F-4):
 *
 * Next's `opengraph-image` file convention emits its generated PNG at an
 * EXTENSIONLESS path (`out/opengraph-image`). GitHub Pages resolves
 * content-type from the file extension alone, so those bytes shipped as
 * `application/octet-stream` — verified live:
 *
 *     /opengraph-image           -> content-type: application/octet-stream
 *     /images/.../card-flag.jpg  -> content-type: image/jpeg
 *
 * The bytes are a valid 1200x630 PNG, so sniffing unfurlers render the card
 * fine; a strict unfurler that trusts content-type can refuse it. The share
 * card is the pre-click claim a recruiter reads before the site ever loads.
 *
 * `scripts/og-png-alias.mjs` (postbuild) copies each generated card to a
 * BYTE-IDENTICAL `.png` sibling, and every route points here. The extensionless
 * original is left in place, so anything already scraped still resolves.
 *
 * Two rules of Next's metadata make this fiddly, and both are load-bearing:
 *
 *   1. A route's `openGraph` object REPLACES an ancestor's wholesale — it does
 *      not merge key-by-key. Any route declaring `openGraph` must restate url,
 *      siteName and locale (that's TA-10, the sibling finding).
 *   2. For the segment that OWNS an opengraph-image file, the convention's
 *      auto-injection beats an explicit `images` entry declared in that
 *      segment's LAYOUT — but a `page`-level (or not-found-level) declaration
 *      does win. That is why the homepage sets its card in app/page.tsx rather
 *      than relying on app/layout.tsx alone.
 *
 * Keeping the paths here means one edit if Next ever moves the convention's
 * output — instead of ten literals drifting apart across app/.
 */

/** The site-wide golden-hour brand card, generated by app/opengraph-image.tsx. */
export const OG_CARD = {
  url: '/opengraph-image.png',
  width: 1200,
  height: 630,
  // Mirrors app/opengraph-image.tsx's own `alt` export. Restated rather than
  // imported so importers don't pull next/og + node:fs into their module graph.
  alt: 'Sky Halisky: AI builder · accessible, privacy-first tools',
  type: 'image/png',
} as const;

/**
 * /accessibility's own measurement-plate card (app/accessibility/opengraph-image.tsx)
 * — the receipt that unfurls, P05.
 */
export const ACCESSIBILITY_OG_CARD = {
  url: '/accessibility/opengraph-image.png',
  width: 1200,
  height: 630,
  type: 'image/png',
} as const;
