import fs from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire('/Users/skypie/Portfolio-3.0-baseline/package.json');const {chromium}=require('playwright-core');
const b=await chromium.launch({executablePath:'/Users/skypie/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-arm64/chrome-headless-shell',headless:true});const rows=fs.existsSync('work/evidence/interactions.json')?JSON.parse(fs.readFileSync('work/evidence/interactions.json')):[];
const routes=JSON.parse(fs.readFileSync('work/evidence/manifest.json')).routes;
try{for(const route of routes){for(const theme of ['light','dark']){if(rows.some(r=>r.route===route&&r.theme===theme))continue;const c=await b.newContext({viewport:{width:390,height:844},colorScheme:theme,reducedMotion:'reduce'});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await c.addInitScript(t=>{localStorage.setItem('theme',t);localStorage.setItem('flagstone-a11y-prefs',JSON.stringify({dark:t==='dark'}));},theme);const p=await c.newPage();await p.goto('http://127.0.0.1:3038'+route,{waitUntil:'load'});const redirects={'/blog/building-accessmap/':'/blog/building-flagstone/','/work/accessmap/':'/work/flagstone/','/work/mutual-mesh/':'/work/'};if(redirects[route])await p.waitForURL('**'+redirects[route],{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready);const focus=[];
for(let i=0;i<35;i++){await p.keyboard.press('Tab');focus.push(await p.evaluate(()=>{const e=document.activeElement,s=getComputedStyle(e),r=e.getBoundingClientRect();return {tag:e.tagName,text:(e.getAttribute('aria-label')||e.textContent).trim().slice(0,100),id:e.id,href:e.getAttribute('href'),outline:s.outline,shadow:s.boxShadow,focusVisible:e.matches(':focus-visible'),rect:{x:r.x,y:r.y,width:r.width,height:r.height}};}));}
const actions=[];
if(route.startsWith('/flagstone/')){await p.locator('#a11y-panel summary').focus();await p.keyboard.press('Enter');actions.push({panelOpen:await p.locator('#a11y-panel').getAttribute('open')!==null});for(const id of ['a11y-dark','a11y-contrast','a11y-reading','a11y-motion']){await p.locator('#'+id).focus();const before=await p.locator('#'+id).getAttribute('aria-pressed');await p.keyboard.press('Space');actions.push({id,before,after:await p.locator('#'+id).getAttribute('aria-pressed'),live:await p.locator('#a11y-live').innerText()});}await p.locator('#a11y-size').focus();await p.keyboard.press('End');actions.push({size:await p.locator('#a11y-size').inputValue(),rootSize:await p.evaluate(()=>getComputedStyle(document.documentElement).fontSize)});await p.locator('#a11y-reset').focus();await p.keyboard.press('Enter');actions.push({reset:await p.locator('#a11y-size').inputValue()});}
rows.push({route,theme,focus,actions,ariaSnapshot:await p.locator('body').ariaSnapshot()});await c.close();console.log(route+' '+theme);}}
}finally{await b.close();fs.writeFileSync('work/evidence/interactions.json',JSON.stringify(rows,null,2));}
